name: Build and test

on:
  push:
    branches: ["feature/setup-project-structure"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project files
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build